### PR TITLE
Rev 1

### PR DESCRIPTION
**Pull request by poshu**
Module and custom placed notification.

### CODE REVIEW

**Comment by deseven** [comment]
Wow, thanks!
I'll check everything tomorrow.

However, why do you think that the module distribution is better? I thought about it before, but all those constants make Notify() calls really monstrous (#wnRB -> WinNotify::#RB, etc). Maybe at least we can rename the module to something smaller, like WN?

Also, you've edited the README.md and it's fine as long as you want to maintain your own fork, but the new description is not really suitable for my repository. If you plan to work on this project we can do it together and i can add you as a collaborator so you'll be able to commit to this repo directly.

**Comment by poshu** [comment]
Actually, it's my very first time on git (full-powered noob!), I moddified the readme.md in case you would not allow the merge.
All of my code is module based, so external libraries need to be module too : it's cleaner, it allow internal functions to be hidden, and it doesn't fill the auto completion with redundant stuff. I usually only "module-ify" library on my comp and don't release the code, but I wanted to learn a bit of github so I thought it was a good idea.
As for the name, you can of course change it, I wanted it to show it was your library, so I went for full name.

The custom placement is really a hack to keep the function call 1:1 with the original, you might not like it.

**Comment by deseven** [comment]
Sorry, i'm going to decline it because i'll be forced to rewrite almost everything you've done.

Reasons:
1. Yeah, i do not like how you did that custom placement thing, i think it should be more clear for the end user. It's not an easy task to integrate that into the current architecture and i need to think how to do that properly.
2. I don't like the module distribution too, but i understand that some people may want to use it that way, so i'll probably do both.
3. The advanced example should include additional inputs for the notification's location and another button to spawn it. That way it'll be much more intuitive.
4. Readme.
5. Commit name.

Anyway, thanks for that. It's nice that someone found that little project useful :)

**Comment by deseven** [comment]
Check [this](https://github.com/deseven/pb-win-notify/commit/d725f42927490669cd64a7db1cbed03c57c64443).
Now you can include wn-module.pbi to use it as a module or wn.pbi to use it like a simple include. Looks much better for me. What do you think?

**Comment by deseven** [comment]
For the custom location i simply [added another notification type](https://github.com/deseven/pb-win-notify/commit/76adf36daf33dc8291cc72e787861e26268b0c51) and it works right out of the box :) Although you must use NotifyStruct() to spawn it properly.
Is this sufficient?

**Comment by poshu** [comment]
Well, with macro, you don't get any information on the arguments of each function, which would be a problem with the very long wnNotify procedure; and as it is you can't access the constants from within another module.

On the other side, yep the custom placed notification is perfect ^^

**Comment by deseven** [comment]
Oh, didn't think about that. What if i'll write macroses with the needed params?

**Comment by deseven** [comment]
Ah, it won't work like that. Okay, i'll think about it.

**Comment by deseven** [comment]
Ended up just [mapping everything with different names](https://github.com/deseven/pb-win-notify/commit/bc473944b281c31c93908da326495103bafb9a17).
I can't (or can i?..) do the same trick with structures, but it seems that IDE doesn't provide autocomplete for structures inside modules at all, so that probably doesn't matter.

**Comment by deseven** [comment]
@poshu please, provide some feedback. Does my current module implementation work for you?

**Comment by poshu** [comment]
I'm very sorry, I won't be able to check it before monday, I don't have
access to my comp until then.

Le dimanche 20 décembre 2015, deseven notifications@github.com a écrit :

> @poshu https://github.com/poshu please, provide some feedback. Does my
> current module implementation work for you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/deseven/pb-win-notify/pull/1#issuecomment-166109300.

## 

Mugi~

**Pull request closed without merging**
